/* MPL-2.0: https://mozilla.org/MPL/2.0/ */
//! Private verified legacy initializer allowance; general calls retain1M cap.
use super::{A64Cpu,cache::CachePlan,dyld_objc_callbacks::ObjcImage};
const ENTRY:u64=0x18002ca8c;
const UUID:[u8;16]=[0x73,0x36,0xd7,0x5f,0x30,0x14,0x33,0xe7,0x84,0x3f,0xe1,0xf3,0x52,0x2f,0xc5,0x2f];
const ORIGINAL:[u8;32]=[0xf6,0x57,0xbd,0xa9,0xf4,0x4f,1,0xa9,0xfd,0x7b,2,0xa9,0xfd,0x83,0,0x91,0xf3,3,4,0xaa,0xf4,3,3,0xaa,0xf5,3,2,0xaa,0xe0,0xbb,0x15,0x90];
const MAPPED:[u8;16]=[0xf6,0x57,0xbd,0xa9,0xf4,0x4f,1,0xa9,0xfd,0x7b,2,0xa9,0xfd,0x83,0,0x91];
#[derive(Default,Clone,Copy,PartialEq,Eq)]struct Work{classes:u64,protocols:u64}
pub(super) struct LegacyBudget{header:u64,images:Vec<u64>,originals:Vec<Vec<u8>>,work:Work,ticks:u64}
fn allowance(count:usize,work:Work)->Result<u64,String>{if count==0||count>4096||work.classes>1_000_000||work.protocols>1_000_000{return Err("legacy workload requires bounded selected image/class/protocol counts".into());}Ok((100_000+count as u64*25_000+(work.classes+work.protocols)*256).min(20_000_000))}
fn metadata_work(cpu:&A64Cpu,headers:&[u64])->Result<Work,String>{
 let mut work=Work::default();
 for &header in headers{let h=cpu.read_bytes(header,32).ok_or("legacy work header unreadable")?;let n=u32::from_le_bytes(h[16..20].try_into().unwrap())as usize;let size=u32::from_le_bytes(h[20..24].try_into().unwrap())as usize;if n>4096||size>1024*1024{return Err("legacy work command budget".into());}let bytes=cpu.read_bytes(header.checked_add(32).ok_or("legacy work header overflow")?,size).ok_or("legacy work commands unreadable")?;let mut at=0usize;let mut segments=Vec::new();let mut text=None;
  for _ in 0..n{let prefix=bytes.get(at..at+8).ok_or("legacy work command truncated")?;let cmd=u32::from_le_bytes(prefix[..4].try_into().unwrap());let len=u32::from_le_bytes(prefix[4..].try_into().unwrap())as usize;if len<8||len%8!=0{return Err("legacy work command alignment".into());}let end=at.checked_add(len).ok_or("legacy work command overflow")?;let b=bytes.get(at..end).ok_or("legacy work command extent")?;if cmd==0x19{if len<72{return Err("legacy work segment truncated".into());}let sections=u32::from_le_bytes(b[64..68].try_into().unwrap())as usize;if sections>4096||72+sections*80!=len{return Err("legacy work section extent".into());}let vm=u64::from_le_bytes(b[24..32].try_into().unwrap());let length=u64::from_le_bytes(b[32..40].try_into().unwrap());if b[8..24].starts_with(b"__TEXT\0"){if text.replace(vm).is_some(){return Err("legacy work duplicate text".into());}}segments.push((vm,length,b));}at=end;
  }if at!=size{return Err("legacy work command count mismatch".into());}let slide=i128::from(header)-i128::from(text.ok_or("legacy work text absent")?);
  for(vm,length,b)in segments{let limit=vm.checked_add(length).ok_or("legacy work segment overflow")?;for s in b[72..].chunks_exact(80){let classes=s[..16].starts_with(b"__objc_classlist");let protocols=s[..16].starts_with(b"__objc_protolist");if !classes&&!protocols{continue;}let addr=u64::from_le_bytes(s[32..40].try_into().unwrap());let size=u64::from_le_bytes(s[40..48].try_into().unwrap());if size%8!=0||size>8_000_000||addr<vm||addr.checked_add(size).ok_or("legacy work section overflow")?>limit{return Err("legacy work class/protocol table bounds".into());}let actual=u64::try_from(i128::from(addr)+slide).map_err(|_|"legacy work slide overflow")?;if size!=0&&cpu.read_bytes(actual,size as usize).is_none(){return Err("legacy work actual class/protocol table unreadable".into());}let target=if classes{&mut work.classes}else{&mut work.protocols};*target=target.checked_add(size/8).filter(|&x|x<=1_000_000).ok_or("legacy work class/protocol count budget")?;}}
 }
 Ok(work)
}
impl LegacyBudget{
 pub(super) fn verified(cpu:&A64Cpu,plan:&CachePlan,images:&[ObjcImage])->Result<Self,String>{
  let main=plan.files.first().ok_or("legacy workload cache absent")?;let header=plan.regions.iter().find(|r|&r.file==main&&r.file_offset==0).ok_or("legacy workload cache header absent")?.vmaddr;
  if super::cache_initializers::functions(cpu,plan,"/usr/lib/libSystem.B.dylib")?!=[ENTRY]{return Err("legacy workload original initializer provider differs".into());}
  let originals=images.iter().map(|image|cpu.read_bytes(image.header,32).map(|bytes|bytes.to_vec()).ok_or("legacy workload header unreadable".to_owned())).collect::<Result<Vec<_>,String>>()?;
  let headers=images.iter().map(|image|image.header).collect::<Vec<_>>();let work=metadata_work(cpu,&headers)?;let result=Self{header,images:headers,originals,work,ticks:allowance(images.len(),work)?};result.validate(cpu,ENTRY)?;echo!("[a64] verified legacy initializer work images={} class_entries={} protocol_entries={} finite_ticks={}; no readiness receipt",images.len(),work.classes,work.protocols,result.ticks);Ok(result)
 }
 pub(super) fn ticks(&self)->u64{self.ticks}
 pub(super) fn validate(&self,cpu:&A64Cpu,entry:u64)->Result<(),String>{
  if entry!=ENTRY||self.ticks!=allowance(self.images.len(),self.work)?{return Err("legacy workload entry/count/budget differs".into());}
  if cpu.read_bytes(self.header.checked_add(88).ok_or("legacy workload header overflow")?,16).is_none_or(|bytes|bytes!=UUID)||cpu.read_bytes(ENTRY,32).is_none_or(|bytes|bytes!=ORIGINAL)||cpu.mapped_permissions(ENTRY).is_none_or(|p|p&4==0)||cpu.read_bytes(0x1800b3aa4,16).is_none_or(|bytes|bytes!=MAPPED)||cpu.mapped_permissions(0x1800b3aa4).is_none_or(|p|p&4==0){return Err("legacy workload cache UUID/initializer/mapped callback provenance differs".into());}
  if self.originals.len()!=self.images.len(){return Err("legacy workload retained selection count differs".into());}let mut seen=std::collections::HashSet::new();for (&header,original)in self.images.iter().zip(&self.originals){if !seen.insert(header)||original.len()!=32||original[..4]!=0xfeedfacfu32.to_le_bytes()||cpu.read_bytes(header,32).is_none_or(|bytes|bytes!=original){return Err("legacy workload selected image identity differs".into());}}
  if metadata_work(cpu,&self.images)?!=self.work{return Err("legacy workload class/protocol metadata changed".into());}
  Ok(())
 }
}
#[cfg(test)]mod tests{use super::*;
 fn fixture()->(A64Cpu,LegacyBudget){let mut cpu=A64Cpu::new_sparse();cpu.map_zeroed(0x10000,4096,1).unwrap();cpu.try_write_bytes(0x10058,&UUID).unwrap();cpu.map_zeroed(ENTRY&!4095,4096,5).unwrap();cpu.try_write_bytes(ENTRY,&ORIGINAL).unwrap();cpu.map_zeroed(0x1800b3000,4096,5).unwrap();cpu.try_write_bytes(0x1800b3aa4,&MAPPED).unwrap();let images:Vec<u64>=(0..300).map(|i|0x20000+i*4096).collect();cpu.map_zeroed(0x20000,300*4096,1).unwrap();for &header in &images{let mut bytes=[0u8;104];for(at,value)in[(0,0xfeedfacfu32),(4,0x100000c),(12,6),(16,1),(20,72),(32,0x19),(36,72)]{bytes[at..at+4].copy_from_slice(&value.to_le_bytes());}bytes[40..47].copy_from_slice(b"__TEXT\0");bytes[56..64].copy_from_slice(&header.to_le_bytes());bytes[64..72].copy_from_slice(&4096u64.to_le_bytes());cpu.try_write_bytes(header,&bytes).unwrap();}let originals=images.iter().map(|&header|cpu.read_bytes(header,32).unwrap().to_vec()).collect();(cpu,LegacyBudget{header:0x10000,images,originals,work:Work::default(),ticks:allowance(300,Work::default()).unwrap()})}
 #[test]fn count_drives_finite_private_cap(){let empty=Work::default();assert_eq!(allowance(300,empty).unwrap(),7_600_000);assert_eq!(allowance(1,empty).unwrap(),125_000);assert_eq!(allowance(4096,empty).unwrap(),20_000_000);assert!(allowance(0,empty).is_err());assert!(allowance(4097,empty).is_err());assert_eq!(allowance(300,Work{classes:1000,protocols:100}).unwrap(),7_881_600);assert!(allowance(300,Work{classes:1_000_001,protocols:0}).is_err());}
 #[test]fn actual_full_width_class_protocol_fields_drive_work_and_mutations_reject(){
  let(mut cpu,mut budget)=fixture();let header=budget.images[0];let mut bytes=cpu.read_bytes(header,104).unwrap().to_vec();bytes.resize(264,0);bytes[20..24].copy_from_slice(&232u32.to_le_bytes());bytes[36..40].copy_from_slice(&232u32.to_le_bytes());bytes[96..100].copy_from_slice(&2u32.to_le_bytes());
  for(at,name,address,size)in[(104,b"__objc_classlist".as_slice(),header+512,16u64),(184,b"__objc_protolist".as_slice(),header+544,8u64)]{bytes[at..at+16].copy_from_slice(name);bytes[at+32..at+40].copy_from_slice(&address.to_le_bytes());bytes[at+40..at+48].copy_from_slice(&size.to_le_bytes());}
  cpu.try_write_bytes(header,&bytes).unwrap();assert!(budget.validate(&cpu,ENTRY).is_err());let work=metadata_work(&cpu,&budget.images).unwrap();assert!(work==Work{classes:2,protocols:1});budget.work=work;budget.ticks=allowance(300,work).unwrap();budget.originals[0]=cpu.read_bytes(header,32).unwrap().to_vec();budget.validate(&cpu,ENTRY).unwrap();
  cpu.try_write_bytes(header+144,&15u64.to_le_bytes()).unwrap();assert!(metadata_work(&cpu,&budget.images).is_err());assert!(budget.validate(&cpu,ENTRY).is_err());
 }
 #[test]fn private_allowance_never_changes_general_bridge_limit(){let(mut cpu,budget)=fixture();let mut bridge=super::super::bridge::GuestBridge::map(&mut cpu,0x200000).unwrap();let call=super::super::bridge::GuestCall{entry:ENTRY,..Default::default()};assert!(bridge.call(&mut cpu,&call,budget.ticks()).unwrap_err().contains("budget outside"));let foreign=super::super::bridge::GuestCall{entry:ENTRY+4,..Default::default()};assert!(bridge.call_legacy_initializer_with_supervisor(&mut cpu,&foreign,&budget,&mut|_,_|Ok(())).is_err());cpu.try_write_bytes(0x10058,&[0;16]).unwrap();assert!(bridge.call_legacy_initializer_with_supervisor(&mut cpu,&call,&budget,&mut|_,_|Ok(())).is_err());}
 #[test]fn retained_headers_original_entry_and_derived_allowance_cannot_change(){let(mut cpu,mut budget)=fixture();budget.ticks+=1;assert!(budget.validate(&cpu,ENTRY).is_err());budget.ticks-=1;cpu.try_write_bytes(budget.images[0]+24,&1u32.to_le_bytes()).unwrap();assert!(budget.validate(&cpu,ENTRY).is_err());cpu.try_write_bytes(budget.images[0]+24,&[0;4]).unwrap();budget.validate(&cpu,ENTRY).unwrap();cpu.try_write_bytes(ENTRY,&[0;4]).unwrap();assert!(budget.validate(&cpu,ENTRY).is_err());}
 #[test]fn foreign_uuid_entry_callback_and_count_are_rejected(){let(mut cpu,mut budget)=fixture();budget.validate(&cpu,ENTRY).unwrap();assert!(budget.validate(&cpu,ENTRY+4).is_err());budget.images.push(budget.images[0]);assert!(budget.validate(&cpu,ENTRY).is_err());budget.images.pop();cpu.try_write_bytes(0x10058,&[0;16]).unwrap();assert!(budget.validate(&cpu,ENTRY).is_err());cpu.try_write_bytes(0x10058,&UUID).unwrap();cpu.try_write_bytes(0x1800b3aa4,&[0;4]).unwrap();assert!(budget.validate(&cpu,ENTRY).is_err());}
}
